version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: reachinbox-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reachinbox
    ports:
      - "3307:3306"

  redis:
    image: redis:7
    container_name: reachinbox-redis
    ports:
      - "6379:6379"
